-- 사용자 타입
INSERT INTO user_types (name)
VALUES ('MENTOR'),
       ('MENTEE');


-- 학교
INSERT INTO colleges (name)
VALUES ('강동대학교'),
       ('경북과학대학교'),
       ('계명문화대학교'),
       ('국제예술대학교'),
       ('대경대학교'),
       ('대동대학교'),
       ('동아보건대학교'),
       ('동원대학교'),
       ('두원공과대학교'),
       ('명지전문대학'),
       ('목포과학대학교'),
       ('백석문화대학교'),
       ('백석예술대학교'),
       ('백제예술대학교'),
       ('부산예술대학교'),
       ('수원여자대학교'),
       ('우송정보대학'),
       ('인천재능대학교'),
       ('장안대학교'),
       ('정화예술대학교'),
       ('제주한라대학교'),
       ('충청대학교'),
       ('한국복지대학교'),
       ('경복대학교'),
       ('김포대학교'),
       ('동서울대학교'),
       ('동주대학교'),
       ('동아방송예술대학교'),
       ('동주대학교'),
       ('두원공과대학교'),
       ('서울예술대학교'),
       ('신안산대학교'),
       ('여주대학교'),
       ('용인예술과학대학교'),
       ('전남도립대학교'),
       ('한양여자대학교'),
       ('가톨릭관동대학교'),
       ('강릉원주대학교'),
       ('강서대학교'),
       ('경기대학교'),
       ('경민대학교'),
       ('경희대학교'),
       ('계명대학교'),
       ('고신대학교'),
       ('광신대학교'),
       ('남서울대학교'),
       ('단국대학교'),
       ('대구가톨릭대학교'),
       ('대구예술대학교'),
       ('대신대학교'),
       ('대진대학교'),
       ('동덕여자대학교'),
       ('동명대학교'),
       ('동아대학교'),
       ('동의대학교'),
       ('디지털서울문화예술대학교'),
       ('목원대학교'),
       ('배재대학교'),
       ('백석대학교'),
       ('서경대학교'),
       ('성결대학교'),
       ('성신여자대학교'),
       ('서울디지털대학교'),
       ('서울사이버대학교'),
       ('송원대학교'),
       ('세한대학교'),
       ('신한대학교'),
       ('안양대학교'),
       ('용인대학교'),
       ('예원예술대학교'),
       ('중부대학교'),
       ('중앙대학교'),
       ('평택대학교'),
       ('한서대학교'),
       ('한일장신대학교'),
       ('한양대학교'),
       ('협성대학교'),
       ('호남신학대학교'),
       ('호서대학교'),
       ('호원대학교'),
       ('홍익대학교');


-- 전공
INSERT INTO majors (name)
VALUES ('피아노'),
       ('작곡'),
       ('드럼'),
       ('베이스'),
       ('기타'),
       ('보컬'),
       ('전자음악'),
       ('관악');


-- 지역
INSERT INTO regional_local_governments (name)
VALUES ('서울특별시'),
       ('부산광역시'),
       ('대구광역시'),
       ('인천광역시'),
       ('광주광역시'),
       ('대전광역시'),
       ('울산광역시'),
       ('세종특별자치시'),
       ('경기도'),
       ('강원특별자치도'),
       ('충청북도'),
       ('충청남도'),
       ('전북특별자치도'),
       ('전라남도'),
       ('경상북도'),
       ('경상남도'),
       ('제주특별자치도');


INSERT INTO basic_local_governments (name, regional_local_government_id)
VALUES ('강남구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('강동구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('강북구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('강서구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('관악구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('광진구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('구로구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('금천구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('노원구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('도봉구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('동대문구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('동작구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('마포구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('서대문구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('서초구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('성동구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('성북구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('송파구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('양천구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('영등포구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('용산구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('은평구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('종로구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('중랑구', (SELECT id FROM regional_local_governments WHERE name = '서울특별시')),
       ('강서구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('금정구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('기장군', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('남구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('동래구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('부산진구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('북구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('사상구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('사하구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('서구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('수영구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('연제구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('영도구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('해운대구', (SELECT id FROM regional_local_governments WHERE name = '부산광역시')),
       ('군위군', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('남구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('달서구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('달성군', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('북구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('서구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('수성구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '대구광역시')),
       ('강화군', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('계양구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('남동구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('미추홀구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('부평구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('서구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('연수구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('옹진군', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '인천광역시')),
       ('광산구', (SELECT id FROM regional_local_governments WHERE name = '광주광역시')),
       ('남구', (SELECT id FROM regional_local_governments WHERE name = '광주광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '광주광역시')),
       ('북구', (SELECT id FROM regional_local_governments WHERE name = '광주광역시')),
       ('서구', (SELECT id FROM regional_local_governments WHERE name = '광주광역시')),
       ('대덕구', (SELECT id FROM regional_local_governments WHERE name = '대전광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '대전광역시')),
       ('서구', (SELECT id FROM regional_local_governments WHERE name = '대전광역시')),
       ('유성구', (SELECT id FROM regional_local_governments WHERE name = '대전광역시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '대전광역시')),
       ('남구', (SELECT id FROM regional_local_governments WHERE name = '울산광역시')),
       ('동구', (SELECT id FROM regional_local_governments WHERE name = '울산광역시')),
       ('북구', (SELECT id FROM regional_local_governments WHERE name = '울산광역시')),
       ('울주군', (SELECT id FROM regional_local_governments WHERE name = '울산광역시')),
       ('중구', (SELECT id FROM regional_local_governments WHERE name = '울산광역시')),
       ('세종시', (SELECT id FROM regional_local_governments WHERE name = '세종특별자치시')),
       ('가평군', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('고양시 덕양구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('고양시 일산동구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('고양시 일산서구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('과천시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('광명시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('광주시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('구리시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('군포시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('김포시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('남양주시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('동두천시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('부천시 소사구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('부천시 오정구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('부천시 원미구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('성남시 분당구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('성남시 수정구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('성남시 중원구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('수원시 권선구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('수원시 영통구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('수원시 장안구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('수원시 팔달구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('시흥시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('안산시 단원구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('안산시 상록구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('안성시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('안양시 동안구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('안양시 만안구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('양주시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('양평군', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('여주시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('연천군', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('오산시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('용인시 기흥구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('용인시 수지구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('용인시 처인구', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('의왕시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('의정부시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('이천시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('파주시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('평택시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('포천시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('하남시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('화성시', (SELECT id FROM regional_local_governments WHERE name = '경기도')),
       ('강릉시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('고성군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('동해시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('삼척시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('속초시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('양구군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('양양군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('영월군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('원주시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('인제군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('정선군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('철원군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('춘천시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('태백시', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('평창군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('홍천군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('화천군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('횡성군', (SELECT id FROM regional_local_governments WHERE name = '강원특별자치도')),
       ('괴산군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('단양군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('보은군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('영동군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('옥천군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('음성군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('제천시', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('증평군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('진천군', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('청주시 상당구', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('청주시 서원구', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('청주시 청원구', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('청주시 흥덕구', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('충주시', (SELECT id FROM regional_local_governments WHERE name = '충청북도')),
       ('계룡시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('공주시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('금산군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('논산시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('당진시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('보령시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('부여군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('서산시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('서천군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('아산시', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('예산군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('천안시 동남구', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('천안시 서북구', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('청양군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('태안군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('홍성군', (SELECT id FROM regional_local_governments WHERE name = '충청남도')),
       ('고창군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('군산시', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('김제시', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('남원시', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('무주군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('부안군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('순창군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('완주군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('익산시', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('임실군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('장수군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('전주시 덕진구', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('전주시 완산구', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('정읍시', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('진안군', (SELECT id FROM regional_local_governments WHERE name = '전북특별자치도')),
       ('강진군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('고흥군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('곡성군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('광양시', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('구례군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('나주시', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('담양군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('목포시', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('무안군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('보성군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('순천시', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('신안군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('여수시', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('영광군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('영암군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('완도군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('장성군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('장흥군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('진도군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('함평군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('해남군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('화순군', (SELECT id FROM regional_local_governments WHERE name = '전라남도')),
       ('경산시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('경주시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('고령군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('구미시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('김천시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('문경시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('봉화군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('상주시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('성주군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('안동시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('영덕군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('영양군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('영주시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('영천시', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('예천군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('울릉군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('울진군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('의성군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('청도군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('청송군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('칠곡군', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('포항시 남구', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('포항시 북구', (SELECT id FROM regional_local_governments WHERE name = '경상북도')),
       ('거제시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('거창군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('고성군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('김해시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('남해군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('밀양시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('사천시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('산청군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('양산시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('의령군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('진주시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창녕군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창원시 마산합포구', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창원시 마산회원구', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창원시 성산구', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창원시 의창구', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('창원시 진해구', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('통영시', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('하동군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('함안군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('함양군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('합천군', (SELECT id FROM regional_local_governments WHERE name = '경상남도')),
       ('서귀포시', (SELECT id FROM regional_local_governments WHERE name = '제주특별자치도')),
       ('제주시', (SELECT id FROM regional_local_governments WHERE name = '제주특별자치도'))
