# Spring Boot
spring:
  application:
    name: umpa-backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/initial-data.sql


# OpenAPI
springdoc:
  api-docs:
    path: /openapi-json

  swagger-ui:
    path: /swagger-ui
    layout: BaseLayout
    tags-sorter: alpha
    operations-sorter: alpha