spring:
  application:
    name: umpa-backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api/docs/openapi-json

  swagger-ui:
    path: /api/docs
    layout: BaseLayout
    tags-sorter: alpha
    operations-sorter: alpha

---

spring:
  config.activate.on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

oauth2:
  providers:
    - name: google
      clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
      clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      loginUrl: https://accounts.google.com/o/oauth2/v2/auth
      tokenUri: https://oauth2.googleapis.com/token
      profileUri: https://www.googleapis.com/oauth2/v3/userinfo
      redirect-uri: https://um-pa.duckdns.org/api/v1/oauth2/google/callback
    - name: kakao
      clientId: ${OAUTH2_KAKAO_CLIENT_ID}
      clientSecret: ${OAUTH2_KAKAO_CLIENT_SECRET}
      loginUrl: https://kauth.kakao.com/oauth/authorize
      tokenUri: https://kauth.kakao.com/oauth/token
      profileUri: https://kapi.kakao.com/v2/user/me
      redirect-uri: https://um-pa.duckdns.org/api/v1/oauth2/kakao/callback
    - name: naver
      clientId: ${OAUTH2_NAVER_CLIENT_ID}
      clientSecret: ${OAUTH2_NAVER_CLIENT_SECRET}
      loginUrl: https://nid.naver.com/oauth2.0/authorize
      tokenUri: https://nid.naver.com/oauth2.0/token
      profileUri: https://openapi.naver.com/v1/nid/me
      redirect-uri: https://um-pa.duckdns.org/api/v1/oauth2/naver/callback
    - name: apple
      redirect-uri: https://um-pa.duckdns.org/api/v1/oauth2/apple/callback
      clientId: ${OAUTH2_APPLE_CLIENT_ID}
      clientSecret: ${OAUTH2_APPLE_CLIENT_SECRET}
      loginUrl: https://appleid.apple.com/auth/authorize
      tokenUri: https://appleid.apple.com/auth/token
      profileUri: https://appleid.apple.com/auth/userinfo

---

spring:
  config.activate.on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

oauth2:
  providers:
    - name: google
      clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
      clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      loginUrl: https://accounts.google.com/o/oauth2/v2/auth
      tokenUri: https://oauth2.googleapis.com/token
      profileUri: https://www.googleapis.com/oauth2/v3/userinfo
      redirect-uri: http://localhost:8080/api/v1/oauth2/google/callback
    - name: kakao
      clientId: ${OAUTH2_KAKAO_CLIENT_ID}
      clientSecret: ${OAUTH2_KAKAO_CLIENT_SECRET}
      loginUrl: https://kauth.kakao.com/oauth/authorize
      tokenUri: https://kauth.kakao.com/oauth/token
      profileUri: https://kapi.kakao.com/v2/user/me
      redirect-uri: http://localhost:8080/api/v1/oauth2/kakao/callback
    - name: naver
      clientId: ${OAUTH2_NAVER_CLIENT_ID}
      clientSecret: ${OAUTH2_NAVER_CLIENT_SECRET}
      loginUrl: https://nid.naver.com/oauth2.0/authorize
      tokenUri: https://nid.naver.com/oauth2.0/token
      profileUri: https://openapi.naver.com/v1/nid/me
      redirect-uri: http://localhost:8080/api/v1/oauth2/naver/callback
    - name: apple
      redirect-uri: http://localhost:8080/api/v1/oauth2/apple/callback
      clientId: ${OAUTH2_APPLE_CLIENT_ID}
      clientSecret: ${OAUTH2_APPLE_CLIENT_SECRET}
      loginUrl: https://appleid.apple.com/auth/authorize
      tokenUri: https://appleid.apple.com/auth/token
      profileUri: https://appleid.apple.com/auth/userinfo
