name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build -x test

      # Add the SSH private key to authenticate with the server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_KEY }}" > ~/.ssh/umpa_key
          chmod 600 ~/.ssh/umpa_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/umpa_key
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy to the home server
      - name: Deploy to Home Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Define variables
          APP_NAME=umpa-backend
          DEPLOY_DIR=~/umpa/$APP_NAME
          JAR_FILE=build/libs/*.jar
          
          # SSH into the home server and prepare the deployment directory
          ssh -T -p $SERVER_PORT $SERVER_HOST << EOF
            mkdir -p $DEPLOY_DIR
            rm -rf $DEPLOY_DIR/*
          EOF
          
          # Copy the built jar to the home server
          scp -P $SERVER_PORT $JAR_FILE $SERVER_HOST:$DEPLOY_DIR
          
          # Restart the Spring Boot application using Java
          ssh -T -p $SERVER_PORT $SERVER_HOST << EOF
            cd $DEPLOY_DIR
            nohup java -jar *.jar --spring.datasource.url=$DB_URL \
              --spring.datasource.username=$DB_USERNAME \
              --spring.datasource.password=$DB_PASSWORD \
              > $DEPLOY_DIR/app.log 2>&1 &
          EOF